# Generated by Django 5.0.3 on 2024-04-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca_Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, unique=True)),
                ('bu', models.CharField(max_length=20)),
                ('nucleo_regional', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NaturezaOrcamentaria_Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha_orc', models.CharField(max_length=100, unique=True)),
                ('n_linha_orc', models.CharField(max_length=10)),
                ('alocacao_dre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade_Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_operacoes', models.CharField(max_length=50, unique=True)),
                ('unidade_financeiro', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=5)),
                ('regiao', models.CharField(blank=True, max_length=10)),
                ('endereco', models.CharField(max_length=300)),
                ('diretor_unidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='unidade',
            name='marca',
        ),
    ]
