# Generated by Django 5.0.3 on 2024-04-20 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_marca_base_naturezaorcamentaria_base_unidade_base_and_more'),
        ('registros', '0008_alter_contrato_anual_fornecedor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NaturezaOrcamentaria',
        ),
        migrations.AddField(
            model_name='unidade_base',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.marca_base', to_field='marca'),
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Unidade',
        ),
    ]
