# Generated by Django 5.0.3 on 2024-04-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorCodigoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='cod_contrato',
            field=models.CharField(default='', max_length=20),
        ),
    ]
