# Generated by Django 5.0.3 on 2024-04-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_contadorcodigocontratoanual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato_anual',
            name='ano_vigencia',
        ),
        migrations.AddField(
            model_name='contrato_anual',
            name='indice_reajuste',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='contrato_anual',
            name='mes_renovacao',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contrato_obras',
            name='indice_reajuste',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='contrato_spot',
            name='indice_reajuste',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='contrato_anual',
            name='distribuicao_mes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrato_anual',
            name='mes_entrada',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrato_obras',
            name='ano_vigencia',
            field=models.CharField(choices=[('2024', '2024'), ('2025', '2025')], max_length=10),
        ),
        migrations.AlterField(
            model_name='contrato_obras',
            name='mes_entrada',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='contrato_spot',
            name='ano_vigencia',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='contrato_spot',
            name='mes_entrada',
            field=models.IntegerField(blank=True),
        ),
    ]
