# Generated by Django 5.0.4 on 2024-04-11 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_rename_cnpj_cpf_fornecedor_documento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedor',
            name='data_registro',
        ),
    ]
