# Generated by Django 5.0.4 on 2024-04-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_remove_fornecedor_data_registro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedor',
            old_name='razaoSocial',
            new_name='razao_social',
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='tipoConta',
            new_name='tipo_conta',
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='tipoPagamento',
            new_name='tipo_pagamento',
        ),
    ]
