# Generated by Django 5.0.3 on 2024-04-20 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_marca_base_naturezaorcamentaria_base_unidade_base_and_more'),
        ('registros', '0007_rename_razaosocial_fornecedor_razao_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato_anual',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registros.fornecedor', to_field='documento'),
        ),
        migrations.AlterField(
            model_name='contrato_anual',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.marca_base', to_field='marca'),
        ),
        migrations.AlterField(
            model_name='contrato_anual',
            name='natureza_orcamentaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.naturezaorcamentaria_base', to_field='linha_orc'),
        ),
        migrations.AlterField(
            model_name='contrato_anual',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.unidade_base', to_field='unidade_operacoes'),
        ),
        migrations.AlterField(
            model_name='contrato_obras',
            name='ano_vigencia',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='contrato_obras',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registros.fornecedor', to_field='documento'),
        ),
        migrations.AlterField(
            model_name='contrato_obras',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.marca_base', to_field='marca'),
        ),
        migrations.AlterField(
            model_name='contrato_obras',
            name='natureza_orcamentaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.naturezaorcamentaria_base', to_field='linha_orc'),
        ),
        migrations.AlterField(
            model_name='contrato_obras',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.unidade_base', to_field='unidade_operacoes'),
        ),
        migrations.AlterField(
            model_name='contrato_spot',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registros.fornecedor', to_field='documento'),
        ),
        migrations.AlterField(
            model_name='contrato_spot',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.marca_base', to_field='marca'),
        ),
        migrations.AlterField(
            model_name='contrato_spot',
            name='natureza_orcamentaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.naturezaorcamentaria_base', to_field='linha_orc'),
        ),
        migrations.AlterField(
            model_name='contrato_spot',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.unidade_base', to_field='unidade_operacoes'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='documento',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
