# Generated by Django 5.0.3 on 2024-04-10 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('registros', '0002_contadorcodigocontrato_contrato_cod_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorCodigoContratoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContadorCodigoContratoObras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ContadorCodigoContratoSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato_Anual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_contrato', models.CharField(blank=True, default='', max_length=20)),
                ('data_registro', models.DateTimeField(auto_now=True)),
                ('ano_vigencia', models.CharField(choices=[(2024, 2024)], max_length=10)),
                ('descricao_servico', models.TextField()),
                ('valor_mensal', models.FloatField(default=0)),
                ('valor_contratado', models.FloatField(default=0)),
                ('mes_entrada', models.IntegerField(default=1)),
                ('distribuicao_mes', models.IntegerField(default=1)),
                ('solicitante', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('links_docs', models.TextField()),
                ('numero_otrs', models.CharField(max_length=100)),
                ('data_registro_otrs', models.CharField(max_length=100)),
                ('contr_prop', models.CharField(max_length=100)),
                ('info_diversas', models.CharField(max_length=200)),
                ('renovacao_automatica', models.CharField(max_length=10)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registros.fornecedor')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.marca')),
                ('natureza_orcamentaria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.naturezaorcamentaria')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato_Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_contrato', models.CharField(blank=True, default='', max_length=20)),
                ('data_registro', models.DateTimeField(auto_now=True)),
                ('ano_vigencia', models.CharField(choices=[(2024, 2024)], max_length=10)),
                ('descricao_servico', models.TextField()),
                ('valor_mensal', models.FloatField(default=0)),
                ('valor_contratado', models.FloatField(default=0)),
                ('mes_entrada', models.IntegerField(default=1)),
                ('distribuicao_mes', models.IntegerField(default=1)),
                ('solicitante', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('links_docs', models.TextField()),
                ('numero_otrs', models.CharField(max_length=100)),
                ('data_registro_otrs', models.CharField(max_length=100)),
                ('contr_prop', models.CharField(max_length=100)),
                ('info_diversas', models.CharField(max_length=200)),
                ('renovacao_automatica', models.CharField(max_length=10)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registros.fornecedor')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.marca')),
                ('natureza_orcamentaria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.naturezaorcamentaria')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato_Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_contrato', models.CharField(blank=True, default='', max_length=20)),
                ('data_registro', models.DateTimeField(auto_now=True)),
                ('ano_vigencia', models.CharField(choices=[(2024, 2024)], max_length=10)),
                ('descricao_servico', models.TextField()),
                ('valor_mensal', models.FloatField(default=0)),
                ('valor_contratado', models.FloatField(default=0)),
                ('mes_entrada', models.IntegerField(default=1)),
                ('distribuicao_mes', models.IntegerField(default=1)),
                ('solicitante', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('links_docs', models.TextField()),
                ('numero_otrs', models.CharField(max_length=100)),
                ('data_registro_otrs', models.CharField(max_length=100)),
                ('contr_prop', models.CharField(max_length=100)),
                ('info_diversas', models.CharField(max_length=200)),
                ('renovacao_automatica', models.CharField(max_length=10)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registros.fornecedor')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.marca')),
                ('natureza_orcamentaria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.naturezaorcamentaria')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.unidade')),
            ],
        ),
        migrations.DeleteModel(
            name='ContadorCodigoContrato',
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
    ]
