# Generated by Django 5.0.4 on 2024-04-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_rename_razaosocial_fornecedor_razao_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato_obras',
            name='ano_vigencia',
            field=models.CharField(max_length=10),
        ),
    ]
