# Generated by Django 5.0.4 on 2024-04-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='endereco',
            field=models.CharField(default='', max_length=150),
        ),
    ]
